#page title
page_title                                : myMouNaMusic                              # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

download_link                             : https://drive.google.com/file/d/1U8eqgGz-vAmarotqtmTS4O6VtMuWmBwu/view?usp=drive_link
appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
portfolio_link                            : https://ceduth.dev                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free +In-app purchases                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : >-
  Plateforme de streaming de musique.
  Artistes, promouvez vous-mêmes votre art tout en générerant des revenus.
app_description2                          : >-
  A localized audio/video music streaming mobile application and platform 
  for local artists to promote their art and generate income, inspired by Spotify.
enable_smart_app_banner                   : false                                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                
your_link                                 : https://ceduth.dev                     
your_city                                 : Conakry, Guinea                                
email_address                             : ceduth@techoutlooks.com
facebook_username                         :                                           
instagram_username                        : ceduth
twitter_username                          : ceduth
github_username                           : techoutlooks
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Librairie
    description                           : Un répertoire audio/video unique de toute la musique locale. Recherche rapide par artiste, genre, etc.
    fontawesome_icon_name                 : play-circle

  - title                                 : Organisez votre contenu
    description                           : Créez et gérez vos playlistes. Ajoutez des items a vos favoris. Evaluez et notez le contenu.
    fontawesome_icon_name                 : magic

  - title                                 : Chat
    description                           : Chattez avec vos artistes préférés.
    fontawesome_icon_name                 : fa-rocketchat

  - title                                 : DRM & In-app purchases
    description                           : Telechargez légalement de la musique grace au systeme intégré de protection des droits d'auteur. 
    fontawesome_icon_name                 : arrow-alt-circle-down
  
  - title                                 : Notifications
    description                           : Recevez des suggestions concernant musique favorite et ce qui fait le buzz autour de vous.
    fontawesome_icon_name                 : sync

  - title                                 : Social Links
    description                           : Retrouvez vos artistes preferes sur leurs plateformes Youtube, Twitter, Instagram, Facebook et Telegram.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Services Relation Publiques & Support Technique accessible 24/7.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
